version: '3'

services:
  app:
    container_name: card_with_graph
    build: .
    environment:
      - PORT=3000
    labels:
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.card-graph.rule=Host(`card-graph.mytestingenlocal.ml`)" # <== Your Domain Name for the https rule
      - "traefik.http.routers.card-graph.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
      - "traefik.http.routers.card-graph.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
      - "traefik.http.services.card-graph.loadbalancer.server.port=3000" # 3000 is the port we proxy to
      # no https
      - "traefik.http.routers.card-graph-http.rule=Host(`card-graph.mytestingenlocal.ml`)" # <== Your Domain Name goes here for the http rule
      - "traefik.http.routers.card-graph-http.entrypoints=web" # <== Defining the entrypoint for http, **ref: line 30
      - "traefik.http.routers.card-graph-http.middlewares=redirect@file" # <== This is a middleware to redirect to https
    networks:
      - web
    env_file:
      - .env

networks:
  web:
    external: true